# Práctica 1 - Limpieza de Datos
### Equipo: 7
#### Grupo: 002 
#### Integrantes: 
#### 1745134 Ramírez Arellano Nathanael
#### 1795417 Mendoza Sanchez Evelin Yamile
#### 1798181 Tello Esparza Jesus Omar

## 1. [Heart Failure Prediction](https://www.kaggle.com/andrewmvd/heart-failure-clinical-data)

### Preparación de los datos

In [2]:
import pandas as pd
import numpy as np
import json

#llamamos el archivo de excel
heartbase = pd.read_csv("heart_failure_clinical_records_dataset.csv")

### Visualización de Datos

- Datos sin manipulación

In [9]:
heartbase

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

- Vemos el tamaño de la base de datos

In [18]:
heartbase.shape

(299, 13)

- Vemos los primeros 5 elementos de todas las columnas

In [19]:
heartbase.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

- Vemos los últimos 5 elementos de todas las columnas

In [26]:
heartbase.tail()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
294                    1   155000.0               1.1           143    1   
295                    0   270000.0               1.2           139    0   
296                    0   742000.0               0.8           138    0   
297                    0   140000.0               1.4           140    1   
298                    0   395000.0               1.6           136    1   

     smoking  time  DEATH_EVENT  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0

- Verificamos los datos nulos (no los hay)

In [18]:
heartbase.isnull().any()

age                         False
anaemia                     False
creatinine_phosphokinase    False
diabetes                    False
ejection_fraction           False
high_blood_pressure         False
platelets                   False
serum_creatinine            False
serum_sodium                False
sex                         False
smoking                     False
time                        False
DEATH_EVENT                 False
dtype: bool

### Cambiar el nombre de las columnas
- En nuestro caso, modificamos los nombres de las columnas al idioma español

In [7]:
heartbase = heartbase.rename(columns = {'age':'Edad','anaemia':'Anemia','creatinine_phosphokinase':'Creatina_Fosfoquinasa','diabetes':'Diabetes','ejection_fraction':'Fraccion_de_Eyeccion',
                           'high_blood_pressure':'Hipertension','platelets':'Plaquetas','serum_creatinine':'Suero_de_Creatinina','serum_sodium':'Suero_de_Sodio','sex':'Sexo',
                           'smoking':'Fumador','time':'Tiempo','DEATH_EVENT':'Muerte'}) #los nombres de las columnas se modificaron al idioma español
#heartbase.rename(columns = {'anaemia':'Anemia')
#heartbase.rename(columns = 'creatinine_phosphokinase':'Creatina_Fosfoquinasa'})
#heartbase.rename(columns = {'diabetes':'Diabetes'})
#heartbase.rename(columns = {'ejection_fraction':'Fraccion_de_Eyeccion'})
#heartbase.rename(columns = {'high_blood_pressure':'Hipertension'})
#heartbase.rename(columns = {'platelets':'Plaquetas'})
#heartbase.rename(columns = {'serum_creatinine':'Suero_de_Creatinina'})
#heartbase.rename(columns = {'serum_sodium':'Suero_de_Sodio'})
#heartbase.rename(columns = {'sex':'Sexo'})
#heartbase.rename(columns = {'smoking':'Fumador'})
#eartbase.rename(columns = {'time':'Tiempo'})
#heartbase.rename(columns = {'DEATH_EVENT':'Muerte'})

### Descripción básica de columnas
- Vemos las columnas

In [8]:
heartbase.columns

Index(['Edad', 'Anemia', 'Creatina_Fosfoquinasa', 'Diabetes',
       'Fraccion_de_Eyeccion', 'Hipertension', 'Plaquetas',
       'Suero_de_Creatinina', 'Suero_de_Sodio', 'Sexo', 'Fumador', 'Tiempo',
       'Muerte'],
      dtype='object')

- Tipos de datos por columnas

In [9]:
heartbase.dtypes

Edad                     float64
Anemia                     int64
Creatina_Fosfoquinasa      int64
Diabetes                   int64
Fraccion_de_Eyeccion       int64
Hipertension               int64
Plaquetas                float64
Suero_de_Creatinina      float64
Suero_de_Sodio             int64
Sexo                       int64
Fumador                    int64
Tiempo                     int64
Muerte                     int64
dtype: object

- Elementos únicos de la columna 'Edad' (La edad del paciente)

In [10]:
print("Edad:")
heartbase.Edad.unique()

Edad:


array([75.   , 55.   , 65.   , 50.   , 90.   , 60.   , 80.   , 62.   ,
       45.   , 49.   , 82.   , 87.   , 70.   , 48.   , 68.   , 53.   ,
       95.   , 58.   , 94.   , 85.   , 69.   , 72.   , 51.   , 57.   ,
       42.   , 41.   , 67.   , 79.   , 59.   , 44.   , 63.   , 86.   ,
       66.   , 43.   , 46.   , 61.   , 81.   , 52.   , 64.   , 40.   ,
       60.667, 73.   , 77.   , 78.   , 54.   , 47.   , 56.   ])

- Elementos únicos de la columna 'Anemia' (Si el paciente tiene Anemia sí:1|no:0)

In [11]:
print("Anemia:")
heartbase.Anemia.unique()

Anemia:


array([0, 1], dtype=int64)

- Elementos únicos de la columna 'Creatina Fosfoquinasa' (Niveles de la enzima en mcg/L)

In [12]:
print("Creatina Fosfoquinasa:")
heartbase.Creatina_Fosfoquinasa.unique()

Creatina Fosfoquinasa:


array([ 582, 7861,  146,  111,  160,   47,  246,  315,  157,  123,   81,
        231,  981,  168,   80,  379,  149,  125,   52,  128,  220,   63,
        148,  112,  122,   60,   70,   23,  249,  159,   94,  855, 2656,
        235,  124,  571,  127,  588, 1380,  553,  129,  577,   91, 3964,
         69,  260,  371,   75,  607,  789,  364, 7702,  318,  109,   68,
        250,  110,  161,  113, 5882,  224,   92,  102,  203,  336,   76,
         55,  280,   78,   84,  115,   66,  897,  154,  144,  133,  514,
         59,  156,   61,  305,  898, 5209,   53,  328,  748, 1876,  936,
        292,  369,  143,  754,  400,   96,  737,  358,  200,  248,  270,
       1808, 1082,  719,  193, 4540,  646,  281, 1548,  805,  291,  482,
        943,  185,  132, 1610, 2261,  233,   30, 1846,  335,   58,  910,
         72,  130, 2334, 2442,  776,  196,  835, 3966,  171,  198,   95,
       1419,  478,  176,  395,   99,  145,  104, 1896,  151,  244,   62,
        121,  418,  167, 1211, 1767,  308,   97,   

- Elementos únicos de la columna 'Diabetes' (Si el paciente tiene diabetes sí:1|no:0)

In [13]:
print("Diabetes:")
heartbase.Diabetes.unique()

Diabetes:


array([0, 1], dtype=int64)

- Elementos únicos de la columna 'Fracción de Eyección' (Porcentaje de sangre que sale del corazón tras cada contracción)

In [14]:
print("Fracción de Eyección:")
heartbase.Fraccion_de_Eyeccion.unique()

Fracción de Eyección:


array([20, 38, 40, 15, 60, 65, 35, 25, 30, 50, 14, 55, 45, 62, 80, 17, 70],
      dtype=int64)

- Elementos únicos de la columna 'Hipertensión' (Si el paciente tiene hipertensión sí:1|no:0)

In [15]:
print("Hipertensión:")
heartbase.Hipertension.unique()

Hipertensión:


array([1, 0], dtype=int64)

- Elementos únicos de la columna 'Plaquetas' (Plaquetas en la sangre medido en kiloplaquetas/mL)

In [16]:
print("Plaquetas:")
heartbase.Plaquetas.unique()

Plaquetas:


array([265000.  , 263358.03, 162000.  , 210000.  , 327000.  , 204000.  ,
       127000.  , 454000.  , 388000.  , 368000.  , 253000.  , 136000.  ,
       276000.  , 427000.  ,  47000.  , 262000.  , 166000.  , 237000.  ,
        87000.  , 297000.  , 289000.  , 149000.  , 196000.  , 284000.  ,
       153000.  , 200000.  , 360000.  , 319000.  , 302000.  , 188000.  ,
       228000.  , 226000.  , 321000.  , 305000.  , 329000.  , 185000.  ,
       218000.  , 194000.  , 310000.  , 271000.  , 451000.  , 140000.  ,
       395000.  , 418000.  , 351000.  , 255000.  , 461000.  , 223000.  ,
       216000.  , 254000.  , 390000.  , 385000.  , 119000.  , 213000.  ,
       274000.  , 244000.  , 497000.  , 374000.  , 122000.  , 243000.  ,
       266000.  , 317000.  , 283000.  , 324000.  , 293000.  , 172000.  ,
       406000.  , 173000.  , 304000.  , 235000.  , 181000.  , 249000.  ,
       219000.  , 318000.  , 221000.  , 298000.  , 286000.  , 621000.  ,
       263000.  , 850000.  , 306000.  , 252000.  , 

- Elementos únicos de la columna 'Suero de Creatinina' (Niveles de este suero en la sangre medido en mg/dL)

In [17]:
print("Suero de Creatinina:")
heartbase.Suero_de_Creatinina.unique()

Suero de Creatinina:


array([1.9 , 1.1 , 1.3 , 2.7 , 2.1 , 1.2 , 1.5 , 9.4 , 4.  , 0.9 , 1.  ,
       0.8 , 1.6 , 1.83, 5.8 , 3.  , 3.5 , 2.3 , 0.6 , 4.4 , 1.4 , 6.8 ,
       2.2 , 2.  , 1.18, 2.9 , 0.7 , 1.7 , 2.5 , 1.8 , 3.2 , 0.75, 3.7 ,
       3.4 , 6.1 , 2.4 , 9.  , 5.  , 0.5 , 3.8 ])

- Elementos únicos de la columna 'Suero de Sodio' (Niveles de este suero en la sangre medido en mEq/L)

In [18]:
print("Suero de Sodio:")
heartbase.Suero_de_Sodio.unique()

Suero de Sodio:


array([130, 136, 129, 137, 116, 132, 131, 138, 133, 140, 127, 121, 135,
       134, 144, 128, 145, 142, 139, 146, 141, 143, 126, 124, 113, 125,
       148], dtype=int64)

- Elementos únicos de la columna 'Sexo' (Mujer:0|Hombre:1)

In [19]:
print("Sexo:")
heartbase.Sexo.unique()

Sexo:


array([1, 0], dtype=int64)

- Elementos únicos de la columna 'Fumador' (Si el paciente fumaba Sí:1|No:0)

In [20]:
print("Fumador:")
heartbase.Fumador.unique()

Fumador:


array([0, 1], dtype=int64)

- Elementos únicos de la columna 'Tiempo' (Periodo de tiempo donde observaban al paciente en días)

In [21]:
print("Tiempo:")
heartbase.Tiempo.unique()

Tiempo:


array([  4,   6,   7,   8,  10,  11,  12,  13,  14,  15,  16,  20,  22,
        23,  24,  26,  27,  28,  29,  30,  31,  32,  33,  35,  38,  40,
        41,  42,  43,  44,  45,  50,  54,  55,  59,  60,  61,  63,  64,
        65,  66,  67,  68,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  82,  83,  85,  86,  87,  88,  90,  91,  94,  95,  96,  97,
       100, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 117,
       118, 119, 120, 121, 123, 126, 129, 130, 134, 135, 140, 145, 146,
       147, 148, 150, 154, 162, 170, 171, 172, 174, 175, 180, 185, 186,
       187, 188, 192, 193, 194, 195, 196, 197, 198, 200, 201, 205, 206,
       207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 220, 230, 231,
       233, 235, 237, 240, 241, 244, 245, 246, 247, 250, 256, 257, 258,
       270, 271, 278, 280, 285], dtype=int64)

- Elementos únicos de la columna 'Muerte' (Si el paciente murió durante el periodo de observación Sí:1|No:0)

In [22]:
print("Muerte:")
heartbase.Muerte.unique()

Muerte:


array([1, 0], dtype=int64)

- Eliminemos algunas columnas que no nos sirven (para la práctica de la limpieza de datos eliminaremos la columna de diabetes)

In [26]:
heartbase = heartbase.drop(['Diabetes'],axis =1) #para la práctica de la limpieza de datos eliminaremos la columna de diabetes
heartbase

Edad  Anemia  Creatina_Fosfoquinasa  Fraccion_de_Eyeccion  Hipertension  \
0    75.0       0                    582                    20             1   
1    55.0       0                   7861                    38             0   
2    65.0       0                    146                    20             0   
3    50.0       1                    111                    20             0   
4    65.0       1                    160                    20             0   
..    ...     ...                    ...                   ...           ...   
294  62.0       0                     61                    38             1   
295  55.0       0                   1820                    38             0   
296  45.0       0                   2060                    60             0   
297  45.0       0                   2413                    38             0   
298  50.0       0                    196                    45             0   

     Plaquetas  Suero_de_Creatinina  Suero_de_Sodio  Sexo  Fumador  Tiempo  \
0    265000.00                  1.9             130     1        0       4   
1    263358.03                  1.1             136     1        0       6   
2    162000.00                  1.3             129     1        1       7   
3    210000.00                  1.9             137     1        0       7   
4    327000.00                  2.7             116     0        0       8   
..         ...                  ...             ...   ...      ...     ...   
294  155000.00                  1.1             143     1        1     270   
295  270000.00                  1.2             139     0        0     271   
296  742000.00                  0.8             138     0        0     278   
297  140000.00                  1.4             140     1        1     280   
298  395000.00                  1.6             136     1        1     285   

     Muerte  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
294       0  
295       0  
296       0  
297       0  
298       0  

[299 rows x 12 columns]

### Clasificación y Agrupación de datos
- Agrupemos a las personas que sí murieron durante el periodo de observación

In [28]:
si_murio = heartbase[heartbase['Muerte']==1]
si_murio

Edad  Anemia  Creatina_Fosfoquinasa  Fraccion_de_Eyeccion  Hipertension  \
0    75.0       0                    582                    20             1   
1    55.0       0                   7861                    38             0   
2    65.0       0                    146                    20             0   
3    50.0       1                    111                    20             0   
4    65.0       1                    160                    20             0   
..    ...     ...                    ...                   ...           ...   
220  73.0       0                    582                    20             0   
230  60.0       0                    166                    30             0   
246  55.0       0                   2017                    25             0   
262  65.0       1                    258                    25             0   
266  55.0       0                   1199                    20             0   

     Plaquetas  Suero_de_Creatinina  Suero_de_Sodio  Sexo  Fumador  Tiempo  \
0    265000.00                 1.90             130     1        0       4   
1    263358.03                 1.10             136     1        0       6   
2    162000.00                 1.30             129     1        1       7   
3    210000.00                 1.90             137     1        0       7   
4    327000.00                 2.70             116     0        0       8   
..         ...                  ...             ...   ...      ...     ...   
220  263358.03                 1.83             134     1        0     198   
230   62000.00                 1.70             127     0        0     207   
246  314000.00                 1.10             138     1        0     214   
262  198000.00                 1.40             129     1        0     235   
266  263358.03                 1.83             134     1        1     241   

     Muerte  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
220       1  
230       1  
246       1  
262       1  
266       1  

[96 rows x 12 columns]

In [29]:
si_murio.to_csv('PacientesFallecidos.csv')

- Creamos un nuevo archivo con la base de datos editada

In [30]:
heartbase.to_csv('NuevaHeartBase.csv')

Con esto terminamos la limpieza de datos y tenemos un nuevo archivo

## 2. [Restaurant Business Rankings 2020](https://www.kaggle.com/michau96/restaurant-business-rankings-2020?select=Future50.csv)

### Preparación de los datos

In [2]:
import pandas as pd
import numpy as np
import json

#llamamos el archivo de excel
comida = pd.read_csv("Future50.csv")

### Visualización de Datos

- Datos sin manipulación

In [4]:
comida

Rank                        Restaurant                  Location  Sales  \
0      1                        Evergreens            Seattle, Wash.     24   
1      2                       Clean Juice           Charlotte, N.C.     44   
2      3                          Slapfish  Huntington Beach, Calif.     21   
3      4                        Clean Eatz          Wilmington, N.C.     25   
4      5                         Pokeworks            Irvine, Calif.     49   
5      6                       Playa Bowls             Belmar,  N.J.     39   
6      7                  The Simple Greek            Blue Bell, Pa.     24   
7      8                         Melt Shop            New York, N.Y.     20   
8      9                        Creamistry      Yorba Linda,  Calif.     24   
9     10              Joella's Hot Chicken           Louisville, Ky.     29   
10    11                     Eggs Up Grill         Spartanburg, S.C.     30   
11    12                          Dog Haus          Pasadena, Calif.     39   
12    13                  Teriyaki Madness             Denver, Colo.     41   
13    14                    Bluestone Lane            New York, N.Y.     48   
14    15                 Original ChopShop              Plano, Texas     21   
15    16                 Rapid Fired Pizza           Kettering, Ohio     24   
16    17           Ike's Love & Sandwiches     San Francisco, Calif.     44   
17    18                    Vitality Bowls         San Ramon, Calif.     37   
18    19         Hawkers Asian Street Fare             Orlando, Fla.     22   
19    20          Maple Street Biscuit Co.         Orange Park, Fla.     39   
20    21                   Bulla Gastrobar               Doral, Fla.     32   
21    22                       Duck Donuts        Mechanicsburg, Pa.     44   
22    23                   The Little Beet            New York, N.Y.     23   
23    24                   Joe & The Juice            New York, N.Y.     47   
24    25                          By Chloe            New York, N.Y.     37   
25    26              Sugarfire Smokehouse             Olivette, Mo.     39   
26    27               Bibibop Asian Grill            Columbus, Ohio     44   
27    28               Bubbakoo's Burritos       Wall Township, N.J.     28   
28    29                Dos Toros Taqueria            New York, N.Y.     28   
29    30                   The Pizza Press           Anaheim, Calif.     27   
30    31                    The Lost Cajun             Frisco, Texas     20   
31    32                        Just Salad            New York, N.Y.     42   
32    33        Jeni's Splendid Ice Creams            Columbus, Ohio     42   
33    34                          Boqueria            New York, N.Y.     27   
34    35         Quickway Japanese Hibachi              Fairfax, Va.     22   
35    36                         Surcheros              Douglas, Ga.     22   
36    37                   Famous Toastery           Charlotte, N.C.     40   
37    38                  Culinary Dropout         Scottsdale, Ariz.     20   
38    39                     Condado Tacos            Columbus, Ohio     38   
39    40           The Flying Biscuit Cafe              Atlanta, Ga.     29   
40    41             Blue Sushi Sake Grill               Omaha, Neb.     49   
41    42                    The Human Bean             Medford, Ore.     47   
42    43   Spitz Mediterranean Street Food       Los Angeles, Calif.     28   
43    44                      Tacos 4 Life              Conway, Ark.     25   
44    45    Pita Mediterranean Street Food             Fairburn, Ga.     38   
45    46                       LA Crawfish            McAllen, Texas     48   
46    47                            &pizza          Washington, D.C.     45   
47    48               Super Duper Burgers     San Francisco, Calif.     39   
48    49                   StoneFire Grill      Agoura Hills, Calif.     31   
49    50  Gus's World Famous Fried Chicken            

- Vemos el tamaño de la base de datos

In [5]:
comida.shape

(50, 9)

- Vemos los primeros 5 elementos de todas las columnas

In [17]:
comida.head()

Rango  Restaurante              Localizacion  Ventas  \
0      1   Evergreens            Seattle, Wash.      24   
1      2  Clean Juice           Charlotte, N.C.      44   
2      3     Slapfish  Huntington Beach, Calif.      21   
3      4   Clean Eatz          Wilmington, N.C.      25   
4      5    Pokeworks            Irvine, Calif.      49   

  Incremento_Anual_de_Ventas  Unidades Incremento_Anual_de_Unidades  \
0                     130.5%        26                       116.7%   
1                     121.9%       105                        94.4%   
2                      81.0%        21                        90.9%   
3                      79.7%        46                        58.6%   
4                      77.1%        50                        56.3%   

   Volumen_de_Unidades Cadena  
0                 1150     No  
1                  560    Yes  
2                 1370    Yes  
3                  685    Yes  
4                 1210    Yes

- Vemos los últimos 5 elementos de todas las columnas

In [18]:
comida.tail()

Rango                       Restaurante           Localizacion  Ventas  \
45     46                       LA Crawfish         McAllen, Texas      48   
46     47                            &pizza       Washington, D.C.      45   
47     48               Super Duper Burgers  San Francisco, Calif.      39   
48     49                   StoneFire Grill   Agoura Hills, Calif.      31   
49     50  Gus's World Famous Fried Chicken         Memphis, Tenn.      44   

   Incremento_Anual_de_Ventas  Unidades Incremento_Anual_de_Unidades  \
45                      17.6%        25                        13.6%   
46                      17.1%        35                         9.4%   
47                      16.9%        16                        14.3%   
48                      16.0%        13                         8.3%   
49                      14.4%        28                         7.7%   

    Volumen_de_Unidades Cadena  
45                 2050    Yes  
46                 1350     No  
47                 2630     No  
48                 2550     No  
49                 1600    Yes

- Verificamos los datos nulos (no los hay)

In [8]:
comida.isnull().any()

Rank           False
Restaurant     False
Location       False
Sales          False
YOY_Sales      False
Units          False
YOY_Units      False
Unit_Volume    False
Franchising    False
dtype: bool

### Cambiar el nombre de las columnas
- En nuestro caso, modificamos los nombres de las columnas al idioma español

In [12]:
comida = comida.rename(columns = {'Rank':'Rango','Restaurant':'Restaurante','Location':'Localizacion','Sales':'Ventas','YOY_Sales':'Incremento_Anual_de_Ventas',
                           'Units':'Unidades','YOY_Units':'Incremento_Anual_de_Unidades','Unit_Volume':'Volumen_de_Unidades','Franchising':'Cadena'}) #los nombres de las columnas se modificaron al idioma español

### Descripción básica de columnas
- Vemos las columnas

In [10]:
comida.columns

Index(['Rango', 'Restaurante', 'Localizacion', 'Ventas',
       'Incremento_Anual_de_Ventas', 'Unidades', 'YOY_Units',
       'Volumen_de_Unidades', 'Cadena'],
      dtype='object')

- Tipos de datos por columnas

In [11]:
comida.dtypes

Rango                          int64
Restaurante                   object
Localizacion                  object
Ventas                         int64
Incremento_Anual_de_Ventas    object
Unidades                       int64
YOY_Units                     object
Volumen_de_Unidades            int64
Cadena                        object
dtype: object

- Elementos únicos de la columna 'Rango' (Posición del restaurante en el ranking)

In [13]:
print("Rango:")
comida.Rango.unique()

Rango:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
      dtype=int64)

- Elementos únicos de la columna 'Restaurante' (Nombre del restaurante)

In [14]:
print("Restaurante:")
comida.Restaurante.unique()

Restaurante:


array(['Evergreens', 'Clean Juice', 'Slapfish', 'Clean Eatz', 'Pokeworks',
       'Playa Bowls', 'The Simple Greek', 'Melt Shop', 'Creamistry',
       "Joella's Hot Chicken", 'Eggs Up Grill', 'Dog Haus',
       'Teriyaki Madness', 'Bluestone Lane', 'Original ChopShop',
       'Rapid Fired Pizza', "Ike's Love & Sandwiches", 'Vitality Bowls',
       'Hawkers Asian Street Fare', 'Maple Street Biscuit Co.',
       'Bulla Gastrobar', 'Duck Donuts', 'The Little Beet',
       'Joe & The Juice', 'By Chloe', 'Sugarfire Smokehouse',
       'Bibibop Asian Grill', "Bubbakoo's Burritos", 'Dos Toros Taqueria',
       'The Pizza Press', 'The Lost Cajun', 'Just Salad',
       "Jeni's Splendid Ice Creams", 'Boqueria',
       'Quickway Japanese Hibachi', 'Surcheros', 'Famous Toastery',
       'Culinary Dropout', 'Condado Tacos', 'The Flying Biscuit Cafe',
       'Blue Sushi Sake Grill', 'The Human Bean',
       'Spitz Mediterranean Street Food', 'Tacos 4 Life',
       'Pita Mediterranean Street Food', '

- Elementos únicos de la columna 'Localización' (Lugar de origen del restaurante)

In [15]:
print("Localización:")
comida.Localizacion.unique()

Localización:


array(['Seattle, Wash.', 'Charlotte, N.C.', 'Huntington Beach, Calif.',
       'Wilmington, N.C.', 'Irvine, Calif.', 'Belmar,  N.J.',
       'Blue Bell, Pa.', 'New York, N.Y.', 'Yorba Linda,  Calif.',
       'Louisville, Ky.', 'Spartanburg, S.C.', 'Pasadena, Calif.',
       'Denver, Colo.', 'Plano, Texas', 'Kettering, Ohio',
       'San Francisco, Calif.', 'San Ramon, Calif.', 'Orlando, Fla.',
       'Orange Park, Fla.', 'Doral, Fla.', 'Mechanicsburg, Pa.',
       'Olivette, Mo.', 'Columbus, Ohio', 'Wall Township, N.J.',
       'Anaheim, Calif.', 'Frisco, Texas', 'Fairfax, Va.', 'Douglas, Ga.',
       'Scottsdale, Ariz.', 'Atlanta, Ga.', 'Omaha, Neb.',
       'Medford, Ore.', 'Los Angeles, Calif.', 'Conway, Ark.',
       'Fairburn, Ga.', 'McAllen, Texas', 'Washington, D.C.',
       'Agoura Hills, Calif.', 'Memphis, Tenn.'], dtype=object)

- Elementos únicos de la columna 'Ventas' (Ventas totales en 2019 en decenas de millones)

In [16]:
print("Ventas:")
comida.Ventas.unique()

Ventas:


array([24, 44, 21, 25, 49, 39, 20, 29, 30, 41, 48, 37, 22, 32, 23, 47, 28,
       27, 42, 40, 38, 45, 31], dtype=int64)

- Elementos únicos de la columna 'Incremento anual de ventas' (Porcentaje de incremento en las ventas con respecto al año pasado)

In [17]:
print("Incremento anual de ventas:")
comida.Incremento_Anual_de_Ventas.unique()

Incremento anual de ventas:


array(['130.5%', '121.9%', '81.0%', '79.7%', '77.1%', '62.9%', '52.5%',
       '39.6%', '36.8%', '35.5%', '35.4%', '34.5%', '34.1%', '33.0%',
       '32.5%', '32.2%', '30.8%', '30.1%', '30.0%', '28.9%', '28.2%',
       '28.0%', '26.5%', '25.9%', '25.6%', '25.4%', '24.6%', '24.3%',
       '24.0%', '23.7%', '23.0%', '22.7%', '22.4%', '22.0%', '21.4%',
       '21.3%', '21.2%', '20.8%', '19.9%', '19.5%', '19.0%', '18.8%',
       '18.4%', '17.8%', '17.6%', '17.1%', '16.9%', '16.0%', '14.4%'],
      dtype=object)

- Elementos únicos de la columna 'Unidades' (Número de establecimientos)

In [18]:
print("Unidades:")
comida.Unidades.unique()

Unidades:


array([ 26, 105,  21,  46,  50,  76,  36,  19,  60,  17,  41,  63,  48,
        12,  35,  71,  77,   7,  33,   8,  90,  69,  14,  15,  37,  31,
        22,  27,  38,  44,  25,  20,  97,  11,  16,  32,  13,  28],
      dtype=int64)

- Elementos únicos de la columna 'Plaquetas' (Plaquetas en la sangre medido en kiloplaquetas/mL)

In [14]:
print("Incremento Anual de Unidades:")
comida.Incremento_Anual_de_Unidades.unique()

Incremento Anual de Unidades:


array(['116.7%', '94.4%', '90.9%', '58.6%', '56.3%', '28.8%', '33.3%',
       '35.7%', '27.7%', '30.8%', '36.7%', '42.9%', '65.8%', '37.1%',
       '20.0%', '29.6%', '29.1%', '24.2%', '40.0%', '10.0%', '14.3%',
       '16.9%', '25.5%', '7.7%', '15.4%', '23.3%', '14.8%', '22.7%',
       '4.0%', '26.7%', '22.2%', '16.7%', '19.0%', '17.6%', '8.0%',
       '19.8%', '6.7%', '10.3%', '13.6%', '9.4%', '8.3%'], dtype=object)

- Elementos únicos de la columna 'Suero de Creatinina' (Niveles de este suero en la sangre medido en mg/dL)

In [15]:
print("Volumen de Unidades:")
comida.Volumen_de_Unidades.unique()

Volumen de Unidades:


array([1150,  560, 1370,  685, 1210,  580,  775, 1260,  465, 1930,  860,
       1200,  890, 1175,  780,  700,  535, 3800, 4300,  530, 2230,  760,
       2800, 2820, 1330,  970, 1375, 1130,  785, 1240, 1050, 4260,  985,
       1230, 1540, 3120, 2755, 1510, 3500, 2700, 1620, 2050, 1350, 2630,
       2550, 1600], dtype=int64)

- Elementos únicos de la columna 'Suero de Sodio' (Niveles de este suero en la sangre medido en mEq/L)

In [16]:
print("Cadena:")
comida.Cadena.unique()

Cadena:


array(['No', 'Yes'], dtype=object)

- Eliminemos algunas columnas que no nos sirven (para la práctica de la limpieza de datos eliminaremos la columna de diabetes)

In [19]:
comida = comida.drop(['Cadena'],axis =1) #para la práctica de la limpieza de datos eliminaremos la columna de cadena
comida

Rango                       Restaurante              Localizacion  Ventas  \
0       1                        Evergreens            Seattle, Wash.      24   
1       2                       Clean Juice           Charlotte, N.C.      44   
2       3                          Slapfish  Huntington Beach, Calif.      21   
3       4                        Clean Eatz          Wilmington, N.C.      25   
4       5                         Pokeworks            Irvine, Calif.      49   
5       6                       Playa Bowls             Belmar,  N.J.      39   
6       7                  The Simple Greek            Blue Bell, Pa.      24   
7       8                         Melt Shop            New York, N.Y.      20   
8       9                        Creamistry      Yorba Linda,  Calif.      24   
9      10              Joella's Hot Chicken           Louisville, Ky.      29   
10     11                     Eggs Up Grill         Spartanburg, S.C.      30   
11     12                          Dog Haus          Pasadena, Calif.      39   
12     13                  Teriyaki Madness             Denver, Colo.      41   
13     14                    Bluestone Lane            New York, N.Y.      48   
14     15                 Original ChopShop              Plano, Texas      21   
15     16                 Rapid Fired Pizza           Kettering, Ohio      24   
16     17           Ike's Love & Sandwiches     San Francisco, Calif.      44   
17     18                    Vitality Bowls         San Ramon, Calif.      37   
18     19         Hawkers Asian Street Fare             Orlando, Fla.      22   
19     20          Maple Street Biscuit Co.         Orange Park, Fla.      39   
20     21                   Bulla Gastrobar               Doral, Fla.      32   
21     22                       Duck Donuts        Mechanicsburg, Pa.      44   
22     23                   The Little Beet            New York, N.Y.      23   
23     24                   Joe & The Juice            New York, N.Y.      47   
24     25                          By Chloe            New York, N.Y.      37   
25     26              Sugarfire Smokehouse             Olivette, Mo.      39   
26     27               Bibibop Asian Grill            Columbus, Ohio      44   
27     28               Bubbakoo's Burritos       Wall Township, N.J.      28   
28     29                Dos Toros Taqueria            New York, N.Y.      28   
29     30                   The Pizza Press           Anaheim, Calif.      27   
30     31                    The Lost Cajun             Frisco, Texas      20   
31     32                        Just Salad            New York, N.Y.      42   
32     33        Jeni's Splendid Ice Creams            Columbus, Ohio      42   
33     34                          Boqueria            New York, N.Y.      27   
34     35         Quickway Japanese Hibachi              Fairfax, Va.      22   
35     36                         Surcheros              Douglas, Ga.      22   
36     37                   Famous Toastery           Charlotte, N.C.      40   
37     38                  Culinary Dropout         Scottsdale, Ariz.      20   
38     39                     Condado Tacos            Columbus, Ohio      38   
39     40           The Flying Biscuit Cafe              Atlanta, Ga.      29   
40     41             Blue Sushi Sake Grill               Omaha, Neb.      49   
41     42                    The Human Bean             Medford, Ore.      47   
42     43   Spitz Mediterranean Street Food       Los Angeles, Calif.      28   
43     44                      Tacos 4 Life              Conway, Ark.      25   
44     45    Pita Mediterranean Street Food             Fairburn, Ga.      38   
45     46                       LA Crawfish            McAllen, Texas      48   
46     47                            &pizza          Washington, D.C.      45   
47     48               Super Duper Burgers     San Francisco, Calif.      39   
48     49                   StoneFi

### Clasificación y Agrupación de datos
- Agrupemos a los restaurantes que no son cadena

In [13]:
no_cadena = comida[comida['Cadena']=="No"]
no_cadena

Rango                      Restaurante           Localizacion  Ventas  \
0       1                       Evergreens         Seattle, Wash.      24   
9      10             Joella's Hot Chicken        Louisville, Ky.      29   
13     14                   Bluestone Lane         New York, N.Y.      48   
14     15                Original ChopShop           Plano, Texas      21   
18     19        Hawkers Asian Street Fare          Orlando, Fla.      22   
20     21                  Bulla Gastrobar            Doral, Fla.      32   
22     23                  The Little Beet         New York, N.Y.      23   
24     25                         By Chloe         New York, N.Y.      37   
25     26             Sugarfire Smokehouse          Olivette, Mo.      39   
26     27              Bibibop Asian Grill         Columbus, Ohio      44   
28     29               Dos Toros Taqueria         New York, N.Y.      28   
31     32                       Just Salad         New York, N.Y.      42   
32     33       Jeni's Splendid Ice Creams         Columbus, Ohio      42   
33     34                         Boqueria         New York, N.Y.      27   
37     38                 Culinary Dropout      Scottsdale, Ariz.      20   
38     39                    Condado Tacos         Columbus, Ohio      38   
40     41            Blue Sushi Sake Grill            Omaha, Neb.      49   
42     43  Spitz Mediterranean Street Food    Los Angeles, Calif.      28   
46     47                           &pizza       Washington, D.C.      45   
47     48              Super Duper Burgers  San Francisco, Calif.      39   
48     49                  StoneFire Grill   Agoura Hills, Calif.      31   

   Incremento_Anual_de_Ventas  Unidades Incremento_Anual_de_Unidades  \
0                      130.5%        26                       116.7%   
9                       35.5%        17                        30.8%   
13                      33.0%        48                        37.1%   
14                      32.5%        12                        20.0%   
18                      30.0%         7                        40.0%   
20                      28.2%         8                        14.3%   
22                      26.5%        12                        33.3%   
24                      25.6%        14                         7.7%   
25                      25.4%        15                        15.4%   
26                      24.6%        37                        23.3%   
28                      24.0%        22                        10.0%   
31                      22.7%        38                        26.7%   
32                      22.4%        44                        22.2%   
33                      22.0%         7                        16.7%   
37                      20.8%         7                        16.7%   
38                      19.9%        15                        15.4%   
40                      19.5%        14                        16.7%   
42                      18.8%        11                        10.0%   
46                      17.1%        35                         9.4%   
47                      16.9%        16                        14.3%   
48                      16.0%        13                         8.3%   

    Volumen_de_Unidades Cadena  
0                  1150     No  
9                  1930     No  
13                 1175     No  
14                 1930     No  
18                 3800     No  
20                 4300     No  
22                 2230     No  
24                 2800     No  
25                 2820     No  
26                 1330     No  
28                 1375     No  
31                 1240     No  
32                 1050     No  
33                 4260     No  
37                 3120     No  
38                 2755     No  
40                 3500     No  
42                 2700     No  
46                 1350     No  
47                 2630     No  
48                 2550     No

In [9]:
no_cadena.to_csv('RestaurantesFueradeCadena.csv')

- Creamos un nuevo archivo con la base de datos editada

In [30]:
comida.to_csv('Nuevacomida.csv')

Con esto terminamos la limpieza de datos y tenemos un nuevo archivo

### Preguntas de interés

1. ¿Para qué me pueden servir estas agrupaciones para la práctica siguiente?

R= Poder tener un mejor resultado de los datos ya que podemos visualizar mejor y tener una limpieza correcta de la base de datos, ya sea eliminando columnas o agrupando valores dentro de la clase en la que esten etiquetados. 

2. Importancia del análisis previo de los datos antes de iniciar las modificaciones.

R= Observar cuales son las variables que podemos eliminar sin afectar el contenido de las bases de datos, además de tener una correcta limpieza de los datos en caso de que haya datos nulos y deseemos rellenarlos con valores neutros ya sea el 0 y así llevar un mejor manejo de los datos.
